In [ ]:
from pymongo import MongoClient
import pandas as pd

In [ ]:
def busca_TRKV(vagao):
    # Conexão com o MongoDB
    client = MongoClient('mongodb+srv://int_dados:e7bUe2bXbKDu3Xzr@rumo-dev2.hbdcrld.mongodb.net/?authSource=admin')

    # Definição do filtro
    filter = {'CarIDNumber': vagao}

    # Consulta
    cursor = client['supervisorio']['TRKV_treated'].find(filter)

    # Converter o cursor em lista e depois em DataFrame
    df = pd.DataFrame(list(cursor))

    # (Opcional) Remover a coluna _id, se não for necessária
    if '_id' in df.columns:
        df.drop('_id', axis=1, inplace=True)

    return df

In [11]:
def busca_z369(vagao):
    # Conexão com o MongoDB
    client = MongoClient('mongodb+srv://int_dados:e7bUe2bXbKDu3Xzr@rumo-dev2.hbdcrld.mongodb.net/?authSource=admin')

    vagao_str = str(vagao) 

    # Definição do filtro
    filter = {"ATIVO_tratado": vagao_str}

    # Consulta
    cursor = client['supervisorio']['z369_trated'].find(filter)

    # Converter o cursor em lista e depois em DataFrame
    df = pd.DataFrame(list(cursor))

    # (Opcional) Remover a coluna _id, se não for necessária
    if '_id' in df.columns:
        df.drop('_id', axis=1, inplace=True)

    return df

In [13]:
def busca_wcm(vagao):
    # Conexão com o MongoDB
    client = MongoClient('mongodb+srv://int_dados:e7bUe2bXbKDu3Xzr@rumo-dev2.hbdcrld.mongodb.net/?authSource=admin')
    vagao_str = str(vagao) 
    # Pipeline de agregação
    pipeline = [
        {
            '$match': {
                'json_documents.json_Identificação do veículo': {
                    '$regex': vagao_str,
                    '$options': 'i'
                }
            }
        },
        {
            '$project': {
                'json_documents': 1,
                '_id': 0
            }
        },
        {
            '$unwind': '$json_documents'
        },
        {
            '$match': {
                'json_documents.json_Identificação do veículo': {
                    '$regex': vagao_str,
                    '$options': 'i'
                }
            }
        }
    ]

    # Executa a agregação
    result = client['supervisorio']['WCM'].aggregate(pipeline)

    # Converte o resultado em DataFrame
    df = pd.DataFrame(list(result))

    # Se quiser expandir o dicionário 'json_documents' em colunas separadas:
    if not df.empty and 'json_documents' in df.columns:
        df = pd.json_normalize(df['json_documents'])

    return df

In [24]:
def busca_dados(vagao):
    df_WCM =  busca_wcm(vagao)
    df_z369 = busca_z369(vagao)
    df_trkv = busca_TRKV(vagao)

    print(len(df_WCM))
    print(len(df_z369))
    print(len(df_trkv))

    return df_WCM,df_z369,df_trkv

In [23]:
vagao_select = 336700

df_WCM,df_z369,df_trkv = busca_dados(vagao_select)

c:\Users\leona\anaconda3\Lib\site-packages\pymongo\pyopenssl_context.py:352: CryptographyDeprecationWarning: Parsed a negative serial number, which is disallowed by RFC 5280. Loading this certificate will cause an exception in the next release of cryptography.
  _crypto.X509.from_cryptography(x509.load_der_x509_certificate(cert))
c:\Users\leona\anaconda3\Lib\site-packages\pymongo\pyopenssl_context.py:352: CryptographyDeprecationWarning: Parsed a negative serial number, which is disallowed by RFC 5280. Loading this certificate will cause an exception in the next release of cryptography.
  _crypto.X509.from_cryptography(x509.load_der_x509_certificate(cert))
c:\Users\leona\anaconda3\Lib\site-packages\pymongo\pyopenssl_context.py:352: CryptographyDeprecationWarning: Parsed a negative serial number, which is disallowed by RFC 5280. Loading this certificate will cause an exception in the next release of cryptography.
  _crypto.X509.from_cryptography(x509.load_der_x509_certificate(cert))

In [57]:
def tratar_WCM(df_WCM):
    # Garantir que o campo de tempo esteja em formato datetime
    df_WCM['json_trem_TrainTime'] = pd.to_datetime(df_WCM['json_trem_TrainTime'])

    # Criar uma coluna apenas com a data (sem hora)
    df_WCM['Data'] = df_WCM['json_trem_TrainTime'].dt.date

    # Agrupar por dia e pegar o maior valor da força de impacto
    df_WCM_max = (
        df_WCM.groupby('Data', as_index=False)['json_Força de pico de impacto da roda (kN)']
        .max()
        .rename(columns={'json_Força de pico de impacto da roda (kN)': 'Maior_Impacto_kN'})
        .sort_values(by='Data', ascending=True)  # ✅ organiza do mais antigo para o mais recente
    )
    return df_WCM_max
    
df_wcm_trated = tratar_WCM(df_WCM)
df_wcm_trated

         Data  Maior_Impacto_kN
0  2025-08-29             51.08
1  2025-09-15             53.26
2  2025-09-27            175.11
3  2025-10-10             41.87
4  2025-10-14            168.05
5  2025-10-19            184.18

In [61]:
def tratar_trkv(df_trkv):

    import pandas as pd
    import numpy as np

    # Supondo que df_trkv já está carregado com suas colunas
    # e que a coluna json_trem_TrainTime contém a data/hora

    # Converter data/hora
    df_trkv['timestr'] = pd.to_datetime(df_trkv['timestr'])
    df_trkv['Data'] = df_trkv['timestr'].dt.date

    # Colunas de impacto (ajuste os nomes exatamente como estão no seu dataframe)
    colunas_impacto = ['A#L_1', 'A#L_2', 'A#R_1', 'A#R_2', 'B#L_1', 'B#L_2', 'B#R_1']

    # Substituir valores 0 por NaN (para ignorar no cálculo)
    df_trkv[colunas_impacto] = df_trkv[colunas_impacto].replace(0, np.nan)

    # Calcular o maior valor por linha (ignorando 0 e NaN)
    df_trkv['Maior_Impacto_Linha'] = df_trkv[colunas_impacto].max(axis=1, skipna=True)

    # Agrupar por data e pegar o maior impacto do dia
    df_trkv_max = (
        df_trkv.groupby('Data', as_index=False)['Maior_Impacto_Linha']
            .max()
            .rename(columns={'Maior_Impacto_Linha': 'Maior_Impacto_Diario'})
            .sort_values(by='Data', ascending=True)
    )

    # ✅ Formatar com duas casas decimais (0.00)
    df_trkv_max['Maior_Impacto_Diario'] = df_trkv_max['Maior_Impacto_Diario'].round(2)
    df_trkv_max['TRKV_MAX_Cunha'] = df_trkv_max['Maior_Impacto_Diario'] 
    return df_trkv_max[['Data','TRKV_MAX_Cunha']]

df_trkv_trated = tratar_trkv(df_trkv)

In [52]:
def tratar_z369(df_z369): 

    # df_z369['timestr'] = pd.to_datetime(df_z369['timestr'])
    # df_z369['Data'] = df_z369['timestr'].dt.date

    df_z369['Texto_Completo'] = (
        df_z369[['TEXTO', 'TEXTO AVARIA', 'TEXTO CAUSA']]
        .fillna('')  # substitui NaN por vazio
        .agg(' | '.join, axis=1)  # concatena linha a linha
        .str.strip(' | ')  # remove separador no fim se faltar campo
    )

    df_z369_trated = df_z369[['NOTA','ATIVO','TP NOTA','STATUS','dt_abertura_trated', 'dt_fechamento_trated' , 'Texto_Completo']]

    df_z369_Aberturas = df_z369_trated[['dt_abertura_trated','TP NOTA','NOTA','Texto_Completo']]
    df_z369_Aberturas["Enveto"] = "Abertura"
    df_z369_Aberturas = df_z369_Aberturas.rename(columns={
        'dt_abertura_trated': 'Data',
    })

    df_z369_fechamentos = df_z369_trated[df_z369_trated['dt_fechamento_trated'].notnull()]
    df_z369_fechamentos = df_z369_fechamentos[['dt_fechamento_trated','TP NOTA','NOTA','Texto_Completo']]
    df_z369_fechamentos = df_z369_fechamentos.rename(columns={
        'dt_fechamento_trated': 'Data',
    })
    df_z369_fechamentos["Enveto"] = "Fechamento"



    # Concatenar os dois dataframes um embaixo do outro
    df_z369_total = pd.concat([df_z369_Aberturas, df_z369_fechamentos], ignore_index=True)

    # Ordenar pela coluna "Data"
    df_z369_total = df_z369_total.sort_values(by='Data', ascending=True).reset_index(drop=True)
    df_z369_total

    return df_z369_total , df_z369_trated


df_z369_total , df_z369_trated = tratar_z369(df_z369)

C:\Users\leona\AppData\Local\Temp\ipykernel_37168\3740303818.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_z369_Aberturas["Enveto"] = "Abertura"

In [58]:
#main def 
def busca_dados(vagao):

    def busca_wcm(vagao):
        # Conexão com o MongoDB
        client = MongoClient('mongodb+srv://int_dados:e7bUe2bXbKDu3Xzr@rumo-dev2.hbdcrld.mongodb.net/?authSource=admin')
        vagao_str = str(vagao) 
        # Pipeline de agregação
        pipeline = [
            {
                '$match': {
                    'json_documents.json_Identificação do veículo': {
                        '$regex': vagao_str,
                        '$options': 'i'
                    }
                }
            },
            {
                '$project': {
                    'json_documents': 1,
                    '_id': 0
                }
            },
            {
                '$unwind': '$json_documents'
            },
            {
                '$match': {
                    'json_documents.json_Identificação do veículo': {
                        '$regex': vagao_str,
                        '$options': 'i'
                    }
                }
            }
        ]

        # Executa a agregação
        result = client['supervisorio']['WCM'].aggregate(pipeline)

        # Converte o resultado em DataFrame
        df = pd.DataFrame(list(result))

        # Se quiser expandir o dicionário 'json_documents' em colunas separadas:
        if not df.empty and 'json_documents' in df.columns:
            df = pd.json_normalize(df['json_documents'])

        return df
    def busca_z369(vagao):
        # Conexão com o MongoDB
        client = MongoClient('mongodb+srv://int_dados:e7bUe2bXbKDu3Xzr@rumo-dev2.hbdcrld.mongodb.net/?authSource=admin')

        vagao_str = str(vagao) 

        # Definição do filtro
        filter = {"ATIVO_tratado": vagao_str}

        # Consulta
        cursor = client['supervisorio']['z369_trated'].find(filter)

        # Converter o cursor em lista e depois em DataFrame
        df = pd.DataFrame(list(cursor))

        # (Opcional) Remover a coluna _id, se não for necessária
        if '_id' in df.columns:
            df.drop('_id', axis=1, inplace=True)

        return df
    def busca_TRKV(vagao):
        # Conexão com o MongoDB
        client = MongoClient('mongodb+srv://int_dados:e7bUe2bXbKDu3Xzr@rumo-dev2.hbdcrld.mongodb.net/?authSource=admin')

        # Definição do filtro
        filter = {'CarIDNumber': vagao}

        # Consulta
        cursor = client['supervisorio']['TRKV_treated'].find(filter)

        # Converter o cursor em lista e depois em DataFrame
        df = pd.DataFrame(list(cursor))

        # (Opcional) Remover a coluna _id, se não for necessária
        if '_id' in df.columns:
            df.drop('_id', axis=1, inplace=True)

        return df
    
    df_WCM =  busca_wcm(vagao)
    df_z369 = busca_z369(vagao)
    df_trkv = busca_TRKV(vagao)

    print(len(df_WCM))
    print(len(df_z369))
    print(len(df_trkv))

    return df_WCM,df_z369,df_trkv

In [67]:
vagao_select = 336700

df_WCM,df_z369,df_trkv = busca_dados(vagao_select)

c:\Users\leona\anaconda3\Lib\site-packages\pymongo\pyopenssl_context.py:352: CryptographyDeprecationWarning: Parsed a negative serial number, which is disallowed by RFC 5280. Loading this certificate will cause an exception in the next release of cryptography.
  _crypto.X509.from_cryptography(x509.load_der_x509_certificate(cert))
c:\Users\leona\anaconda3\Lib\site-packages\pymongo\pyopenssl_context.py:352: CryptographyDeprecationWarning: Parsed a negative serial number, which is disallowed by RFC 5280. Loading this certificate will cause an exception in the next release of cryptography.
  _crypto.X509.from_cryptography(x509.load_der_x509_certificate(cert))
c:\Users\leona\anaconda3\Lib\site-packages\pymongo\pyopenssl_context.py:352: CryptographyDeprecationWarning: Parsed a negative serial number, which is disallowed by RFC 5280. Loading this certificate will cause an exception in the next release of cryptography.
  _crypto.X509.from_cryptography(x509.load_der_x509_certificate(cert))

48
11
7

In [ ]:
def tratar_dfs(df_WCM,df_z369,df_trkv):

    def tratar_trkv(df_trkv):

        import pandas as pd
        import numpy as np

        # Supondo que df_trkv já está carregado com suas colunas
        # e que a coluna json_trem_TrainTime contém a data/hora

        # Converter data/hora
        df_trkv['timestr'] = pd.to_datetime(df_trkv['timestr'])
        df_trkv['Data'] = df_trkv['timestr'].dt.date

        # Colunas de impacto (ajuste os nomes exatamente como estão no seu dataframe)
        colunas_impacto = ['A#L_1', 'A#L_2', 'A#R_1', 'A#R_2', 'B#L_1', 'B#L_2', 'B#R_1']

        # Substituir valores 0 por NaN (para ignorar no cálculo)
        df_trkv[colunas_impacto] = df_trkv[colunas_impacto].replace(0, np.nan)

        # Calcular o maior valor por linha (ignorando 0 e NaN)
        df_trkv['Maior_Impacto_Linha'] = df_trkv[colunas_impacto].max(axis=1, skipna=True)

        # Agrupar por data e pegar o maior impacto do dia
        df_trkv_max = (
            df_trkv.groupby('Data', as_index=False)['Maior_Impacto_Linha']
                .max()
                .rename(columns={'Maior_Impacto_Linha': 'Maior_Impacto_Diario'})
                .sort_values(by='Data', ascending=True)
        )

        # ✅ Formatar com duas casas decimais (0.00)
        df_trkv_max['Maior_Impacto_Diario'] = df_trkv_max['Maior_Impacto_Diario'].round(2)
        df_trkv_max['TRKV_MAX_Cunha'] = df_trkv_max['Maior_Impacto_Diario'] 
        return df_trkv_max[['Data','TRKV_MAX_Cunha']]
    df_trkv_trated = tratar_trkv(df_trkv)

    def tratar_WCM(df_WCM):
        # Garantir que o campo de tempo esteja em formato datetime
        df_WCM['json_trem_TrainTime'] = pd.to_datetime(df_WCM['json_trem_TrainTime'])

        # Criar uma coluna apenas com a data (sem hora)
        df_WCM['Data'] = df_WCM['json_trem_TrainTime'].dt.date

        # Agrupar por dia e pegar o maior valor da força de impacto
        df_WCM_max = (
            df_WCM.groupby('Data', as_index=False)['json_Força de pico de impacto da roda (kN)']
            .max()
            .rename(columns={'json_Força de pico de impacto da roda (kN)': 'Maior_Impacto_kN'})
            .sort_values(by='Data', ascending=True)  # ✅ organiza do mais antigo para o mais recente
        )
        return df_WCM_max
    df_wcm_trated = tratar_WCM(df_WCM)
    
    def tratar_z369(df_z369): 

        # df_z369['timestr'] = pd.to_datetime(df_z369['timestr'])
        # df_z369['Data'] = df_z369['timestr'].dt.date

        df_z369['Texto_Completo'] = (
            df_z369[['TEXTO', 'TEXTO AVARIA', 'TEXTO CAUSA']]
            .fillna('')  # substitui NaN por vazio
            .agg(' | '.join, axis=1)  # concatena linha a linha
            .str.strip(' | ')  # remove separador no fim se faltar campo
        )

        df_z369_trated = df_z369[['NOTA','ATIVO','TP NOTA','STATUS','dt_abertura_trated', 'dt_fechamento_trated' , 'Texto_Completo']]

        df_z369_Aberturas = df_z369_trated[['dt_abertura_trated','TP NOTA','NOTA','Texto_Completo']]
        df_z369_Aberturas["Enveto"] = "Abertura"
        df_z369_Aberturas = df_z369_Aberturas.rename(columns={
            'dt_abertura_trated': 'Data',
        })

        df_z369_fechamentos = df_z369_trated[df_z369_trated['dt_fechamento_trated'].notnull()]
        df_z369_fechamentos = df_z369_fechamentos[['dt_fechamento_trated','TP NOTA','NOTA','Texto_Completo']]
        df_z369_fechamentos = df_z369_fechamentos.rename(columns={
            'dt_fechamento_trated': 'Data',
        })
        df_z369_fechamentos["Enveto"] = "Fechamento"



        # Concatenar os dois dataframes um embaixo do outro
        df_z369_total = pd.concat([df_z369_Aberturas, df_z369_fechamentos], ignore_index=True)

        # Ordenar pela coluna "Data"
        df_z369_total = df_z369_total.sort_values(by='Data', ascending=True).reset_index(drop=True)
        df_z369_total

        return df_z369_total , df_z369_trated
    df_z369_total , df_z369_trated = tratar_z369(df_z369)
    
    return df_trkv_trated, df_wcm_trated ,df_z369_total , df_z369_trated
    
df_trkv_trated ,df_wcm_trated ,df_z369_total , df_z369_trated = tratar_dfs(df_WCM,df_z369,df_trkv)

C:\Users\leona\AppData\Local\Temp\ipykernel_37168\2644617681.py:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_z369_Aberturas["Enveto"] = "Abertura"

In [73]:
df_z369_total

,Data,TP NOTA,NOTA,Texto_Completo,Enveto
0,2024-01-05,M8,23651936,Análise Acionamento - Inspeção de DDV | Anális...,Abertura
1,2024-02-12,M8,23681796,INSP. LONGARINA PRATO OU OBILONGO | INSP. LONG...,Abertura
2,2024-03-28,M1,23518544,REVI MONITORADO | *Amort:Prato Pião* | cab A e...,Abertura
3,2024-04-15,M1,23733050,REVI MONITORADO | *Freio:Válvula de Freio* | V...,Abertura
4,2024-04-25,M8,23681796,INSP. LONGARINA PRATO OU OBILONGO | INSP. LONG...,Fechamento
5,2024-05-10,M1,23733050,REVI MONITORADO | *Freio:Válvula de Freio* | V...,Fechamento
6,2024-06-06,M3,23771970,VGH DETECTOR ACÚSTICO ROLAMENTO(1E OU | VGH DE...,Abertura
7,2024-06-06,M5,23771971,MC 07/06/2024 RUMO PMV OFVRCLAR | Rodeiro avar...,Abertura
8,2024-06-07,M5,23771971,MC 07/06/2024 RUMO PMV OFVRCLAR | Rodeiro avar...,Fechamento
9,2024-06-07,M3,23771970,VGH DETECTOR ACÚSTICO ROLAMENTO(1E OU | VGH DE...,Fechamento
10,2024-06-07,M8,23651936,Análise Acionamento - Inspeção de DDV | Anális...,Fechamento
11,2024-06-07,M1,23518544,REVI MONITORADO | *Amort:Prato Pião* | cab A e...,Fechamento
12,2024-10-10,M8,23865496,RG Truque | RG Truque | RG Truque,Abertura
13,2025-03-20,M8,23865496,RG Truque | RG Truque | RG Truque,Fechamento
14,2025-03-26,M8,23992288,INSPEÇÃO BATENTE TRASEIRO DO ACT 2025 | INSPEÇ...,Abertura
15,2025-07-30,M2,24088302,TR|CUNHA|TRKV|ALTURA|45mm | *Amort:Cunha Alta*...,Abertura
16,2025-08-19,M7,24113404,MP T9 26/08/2025 OFVRCLAR RUMO | Revisão RA,Abertura
17,2025-08-19,M5,24113751,Cunha de Fricção Avariada | Cunha de Fricção A...,Abertura
18,2025-08-26,M2,24088302,TR|CUNHA|TRKV|ALTURA|45mm | *Amort:Cunha Alta*...,Fechamento
19,2025-08-26,M5,24113751,Cunha de Fricção Avariada | Cunha de Fricção A...,Fechamento
20,2025-08-26,M8,23992288,INSPEÇÃO BATENTE TRASEIRO DO ACT 2025 | INSPEÇ...,Fechamento
21,2025-08-29,M7,24113404,MP T9 26/08/2025 OFVRCLAR RUMO | Revisão RA,Fechamento

In [ ]:
def inserir_wcm_hist(df_wcm_trated):
    df_wcm_trated_histgeral = df_wcm_trated.copy()
    df_wcm_trated_histgeral['TP NOTA'] = "Passagem wcm"
    df_wcm_trated_histgeral['NOTA'] = "wcm_" + df_wcm_trated_histgeral['Data'].astype(str)
    df_wcm_trated_histgeral['Texto_Completo'] = "Maior_Impacto_kN = " + df_wcm_trated_histgeral['Maior_Impacto_kN'].astype(str)

    df_wcm_trated_ab = df_wcm_trated_histgeral.copy()
    df_wcm_trated_ab['Evento'] = "Abertura"

    df_wcm_trated_fx = df_wcm_trated_histgeral.copy()
    df_wcm_trated_fx['Evento'] = "Fechamento"

    # Agora sim, cada um é independente
    df_wcm_total = pd.concat([df_wcm_trated_ab, df_wcm_trated_fx], ignore_index=True)
    df_wcm_total = df_wcm_total[['Data','TP NOTA','NOTA','Texto_Completo','Evento']]
    df_wcm_total
    return df_wcm_total

,Data,Maior_Impacto_kN,TP NOTA,NOTA,Texto_Completo,Evento
0,2025-08-29,51.08,Passagem WCM,WCM_2025-08-29,Maior_Impacto_kN = 51.08,Fechamento
1,2025-09-15,53.26,Passagem WCM,WCM_2025-09-15,Maior_Impacto_kN = 53.26,Fechamento
2,2025-09-27,175.11,Passagem WCM,WCM_2025-09-27,Maior_Impacto_kN = 175.11,Fechamento
3,2025-10-10,41.87,Passagem WCM,WCM_2025-10-10,Maior_Impacto_kN = 41.87,Fechamento
4,2025-10-14,168.05,Passagem WCM,WCM_2025-10-14,Maior_Impacto_kN = 168.05,Fechamento
5,2025-10-19,184.18,Passagem WCM,WCM_2025-10-19,Maior_Impacto_kN = 184.18,Fechamento
6,2025-08-29,51.08,Passagem WCM,WCM_2025-08-29,Maior_Impacto_kN = 51.08,Fechamento
7,2025-09-15,53.26,Passagem WCM,WCM_2025-09-15,Maior_Impacto_kN = 53.26,Fechamento
8,2025-09-27,175.11,Passagem WCM,WCM_2025-09-27,Maior_Impacto_kN = 175.11,Fechamento
9,2025-10-10,41.87,Passagem WCM,WCM_2025-10-10,Maior_Impacto_kN = 41.87,Fechamento
10,2025-10-14,168.05,Passagem WCM,WCM_2025-10-14,Maior_Impacto_kN = 168.05,Fechamento
11,2025-10-19,184.18,Passagem WCM,WCM_2025-10-19,Maior_Impacto_kN = 184.18,Fechamento

In [ ]:
def inserir_trkv_hist(df_trkv_trated):
    df_trkv_trated_histgeral = df_trkv_trated
    df_trkv_trated_histgeral['TP NOTA'] = "Passagem trkv"
    df_trkv_trated_histgeral['NOTA'] = "trkv_" + df_trkv_trated_histgeral['Data'].astype(str)
    df_trkv_trated_histgeral['Texto_Completo'] = "TRKV_MAX_Cunha = " + df_trkv_trated_histgeral['TRKV_MAX_Cunha'].astype(str)
    df_trkv_trated_histgeral[['Data','TP NOTA','NOTA','TP NOTA']]

    df_trkv_trated_ab = df_trkv_trated_histgeral
    df_trkv_trated_ab['Evento'] = "Abertura"

    df_trkv_trated_fx = df_trkv_trated_histgeral
    df_trkv_trated_fx['Evento'] = "Fechamento"

    df_trkv_total = pd.concat([df_trkv_trated_ab, df_trkv_trated_fx], ignore_index=True)
    df_trkv_total = df_trkv_total[['Data','TP NOTA','NOTA','Texto_Completo','Evento']] 
    return df_trkv_total

In [109]:
df_trkv_trated_histgeral = df_trkv_trated.copy()
df_trkv_trated_histgeral['TP NOTA'] = "Passagem trkv"
df_trkv_trated_histgeral['NOTA'] = "trkv_" + df_trkv_trated_histgeral['Data'].astype(str)
df_trkv_trated_histgeral['Texto_Completo'] = "TRKV_MAX_Cunha = " + df_trkv_trated_histgeral['TRKV_MAX_Cunha'].astype(str)

df_trkv_trated_ab = df_trkv_trated_histgeral.copy()
df_trkv_trated_ab['Evento'] = "Abertura"

df_trkv_trated_fx = df_trkv_trated_histgeral.copy()
df_trkv_trated_fx['Evento'] = "Fechamento"

# Agora sim, cada um é independente
df_trkv_total = pd.concat([df_trkv_trated_ab, df_trkv_trated_fx], ignore_index=True)
df_trkv_total = df_trkv_total[['Data','TP NOTA','NOTA','Texto_Completo','Evento']]
df_trkv_total

,Data,TP NOTA,NOTA,Texto_Completo,Evento
0,2025-01-10,Passagem trkv,trkv_2025-01-10,TRKV_MAX_Cunha = 26.11,Abertura
1,2025-06-09,Passagem trkv,trkv_2025-06-09,TRKV_MAX_Cunha = 25.63,Abertura
2,2025-06-10,Passagem trkv,trkv_2025-06-10,TRKV_MAX_Cunha = 28.02,Abertura
3,2025-09-15,Passagem trkv,trkv_2025-09-15,TRKV_MAX_Cunha = 25.15,Abertura
4,2025-09-27,Passagem trkv,trkv_2025-09-27,TRKV_MAX_Cunha = 28.02,Abertura
5,2025-10-10,Passagem trkv,trkv_2025-10-10,TRKV_MAX_Cunha = nan,Abertura
6,2025-10-19,Passagem trkv,trkv_2025-10-19,TRKV_MAX_Cunha = 28.47,Abertura
7,2025-01-10,Passagem trkv,trkv_2025-01-10,TRKV_MAX_Cunha = 26.11,Fechamento
8,2025-06-09,Passagem trkv,trkv_2025-06-09,TRKV_MAX_Cunha = 25.63,Fechamento
9,2025-06-10,Passagem trkv,trkv_2025-06-10,TRKV_MAX_Cunha = 28.02,Fechamento
10,2025-09-15,Passagem trkv,trkv_2025-09-15,TRKV_MAX_Cunha = 25.15,Fechamento
11,2025-09-27,Passagem trkv,trkv_2025-09-27,TRKV_MAX_Cunha = 28.02,Fechamento
12,2025-10-10,Passagem trkv,trkv_2025-10-10,TRKV_MAX_Cunha = nan,Fechamento
13,2025-10-19,Passagem trkv,trkv_2025-10-19,TRKV_MAX_Cunha = 28.47,Fechamento

In [101]:
df_trkv_trated_ab['Evento'] ="Abertura"
df_trkv_trated_ab['Evento']

0    Abertura
1    Abertura
2    Abertura
3    Abertura
4    Abertura
5    Abertura
6    Abertura
Name: Evento, dtype: object

In [90]:
df_trkv_total = inserir_trkv_hist(df_trkv_trated)
df_trkv_total

,Data,TP NOTA,NOTA,Texto_Completo,Evento
0,2025-01-10,Passagem trkv,trkv_2025-01-10,TRKV_MAX_Cunha = 26.11,Fechamento
1,2025-06-09,Passagem trkv,trkv_2025-06-09,TRKV_MAX_Cunha = 25.63,Fechamento
2,2025-06-10,Passagem trkv,trkv_2025-06-10,TRKV_MAX_Cunha = 28.02,Fechamento
3,2025-09-15,Passagem trkv,trkv_2025-09-15,TRKV_MAX_Cunha = 25.15,Fechamento
4,2025-09-27,Passagem trkv,trkv_2025-09-27,TRKV_MAX_Cunha = 28.02,Fechamento
5,2025-10-10,Passagem trkv,trkv_2025-10-10,TRKV_MAX_Cunha = nan,Fechamento
6,2025-10-19,Passagem trkv,trkv_2025-10-19,TRKV_MAX_Cunha = 28.47,Fechamento
7,2025-01-10,Passagem trkv,trkv_2025-01-10,TRKV_MAX_Cunha = 26.11,Fechamento
8,2025-06-09,Passagem trkv,trkv_2025-06-09,TRKV_MAX_Cunha = 25.63,Fechamento
9,2025-06-10,Passagem trkv,trkv_2025-06-10,TRKV_MAX_Cunha = 28.02,Fechamento
10,2025-09-15,Passagem trkv,trkv_2025-09-15,TRKV_MAX_Cunha = 25.15,Fechamento
11,2025-09-27,Passagem trkv,trkv_2025-09-27,TRKV_MAX_Cunha = 28.02,Fechamento
12,2025-10-10,Passagem trkv,trkv_2025-10-10,TRKV_MAX_Cunha = nan,Fechamento
13,2025-10-19,Passagem trkv,trkv_2025-10-19,TRKV_MAX_Cunha = 28.47,Fechamento

In [83]:
df_trkv_trated

         Data  TRKV_MAX_Cunha
0  2025-01-10           26.11
1  2025-06-09           25.63
2  2025-06-10           28.02
3  2025-09-15           25.15
4  2025-09-27           28.02
5  2025-10-10             NaN
6  2025-10-19           28.47