In [1]:
import numpy as np
import plotly.express as px
import pandas as pd
from datetime import datetime
import re
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
import time
import streamlit as st
from pymongo import MongoClient
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

In [ ]:
MONGO_URI = "mongodb+srv://int_dados:e7bUe2bXbKDu3Xzr@rumo-dev2.hbdcrld.mongodb.net/?authSource=admin"
DB_NAME = "supervisorio"

In [ ]:
import asyncio
from concurrent.futures import ThreadPoolExecutor
import pandas as pd
import os


def salvar_parquet(df, path):
    # garante que a pasta existe
    os.makedirs(os.path.dirname(path), exist_ok=True)
    df.to_parquet(path, index=False, engine="pyarrow")


async def salvar_tudo_assincrono(dfs, paths):
    loop = asyncio.get_event_loop()

    with ThreadPoolExecutor() as executor:
        tarefas = [
            loop.run_in_executor(executor, salvar_parquet, df, path)
            for df, path in zip(dfs, paths)
        ]

        await asyncio.gather(*tarefas)

def inserir_wcm_hist(df_wcm_trated):
    df_wcm_trated_histgeral = df_wcm_trated.copy()
    print(df_wcm_trated)
    # 1) Garantir datetime (com hora) na coluna Data
    df_wcm_trated_histgeral['INICIO'] = pd.to_datetime(
        df_wcm_trated_histgeral['Data'])
    df_wcm_trated_histgeral['Tipo_Evento'] = "Passagem wcm"
    # + \            df_wcm_trated_histgeral['Data'].astype(str)
    df_wcm_trated_histgeral['Evento'] = "wcm"

    df_wcm_trated_histgeral['Texto_Completo'] = "Maior_Impacto_kN = " + \
        df_wcm_trated_histgeral['Maior_Impacto_kN'].astype(str)

    df_wcm_trated_histgeral["Data"] = pd.to_datetime(
        df_wcm_trated_histgeral["Data"], format="%Y-%m-%d %H:%M")
    df_wcm_trated_histgeral["FIM"] = (
        df_wcm_trated_histgeral["Data"] + pd.to_timedelta(12, unit="h")
    )
    df_wcm_trated_histgeral['Tipo_Evento'] = "WCM"

    df_wcm_total = df_wcm_trated_histgeral[[
        'Evento', 'INICIO', 'FIM', 'Texto_Completo', 'Tipo_Evento']]

    return df_wcm_total

In [21]:
df_164   = pd.read_parquet("temp/df_164.parquet")
df_trkv  = pd.read_parquet("temp/df_trkv.parquet")
df_WCM   = pd.read_parquet("temp/df_WCM.parquet")
df_z369  = pd.read_parquet("temp/df_z369.parquet")
df_z851  = pd.read_parquet("temp/df_z851.parquet")
df_z1568 = pd.read_parquet("temp/df_z1568.parquet")

In [ ]:
df_z851

In [ ]:
# Conversões sem alterar as colunas originais
dt_164     = pd.to_datetime(df_164['DT_CARGA'], errors='coerce')
dt_trkv    = pd.to_datetime(df_trkv['data_sincronizacao'], errors='coerce')
dt_WCM     = pd.to_datetime(df_WCM['json_trem_TrainTime'], errors='coerce')
dt_z369    = pd.to_datetime(df_z369['dt_last_udate_trated'], errors='coerce')
dt_z851    = pd.to_datetime(df_z851['Atualizacao'], errors='coerce')
dt_z1568   = pd.to_datetime(df_z1568['dt_fim_trated'], errors='coerce')

# Datas mais recentes
data_mais_recente_164   = dt_164.max()
data_mais_recente_trkv  = dt_trkv.max()
data_mais_recente_WCM   = dt_WCM.max()
data_mais_recente_z369  = dt_z369.max()
data_mais_recente_z851  = dt_z851.max()
data_mais_recente_z1568 = dt_z1568.max()

print("164:", data_mais_recente_164)
print("TRKV:", data_mais_recente_trkv)
print("WCM:", data_mais_recente_WCM)
print("Z369:", data_mais_recente_z369)
print("Z851:", data_mais_recente_z851)
print("Z1568:", data_mais_recente_z1568)

In [ ]:
def tratar_WCM(df_WCM):

    # Garantir datetime
    df_WCM['json_trem_TrainTime'] = pd.to_datetime(
        df_WCM['json_trem_TrainTime'], errors='coerce'
    )

    # Criar coluna somente com a data
    df_WCM['Data'] = df_WCM['json_trem_TrainTime'].dt.date

    # Agrupamento por veículo + data
    df_WCM_max = (
        df_WCM.groupby(
            ['json_Identificação do veículo', 'Data'],
            as_index=False
        )['json_Força de pico de impacto da roda (kN)']
        .max()
        .rename(columns={
            'json_Força de pico de impacto da roda (kN)': 'Maior_Impacto_kN'
        })
        .sort_values(by=['json_Identificação do veículo', 'Data'])
    )
    df_WCM_max['key'] = df_WCM_max['json_Identificação do veículo'].str.split(
    ).str[-1].astype(int)

    return df_WCM_max

In [ ]:


df_trkv["max_valor"] = df_trkv[["A#L_1", "A#L_2", "A#R_1",
                                "A#R_2", "B#L_1", "B#L_2", "B#R_1", "B#R_2"]].max(axis=1)
df_trkv_filtred = df_trkv[["CarIDInitial",
                            "CarIDNumber", "timestr", "max_valor"]]

df_trkv_filtred = df_trkv_filtred[df_trkv_filtred["CarIDInitial"].notna()]
df_trkv_filtred = df_trkv_filtred[df_trkv_filtred["max_valor"].notna()]
df_trkv_filtred['timestr'] = pd.to_datetime(
    df_trkv_filtred['timestr'], format="%d/%m/%Y %H:%M:%S", errors='coerce')
df_trkv_filtred['key'] = df_trkv_filtred['CarIDNumber'].astype(int)

df_z851['key'] = df_z851['EQUNR'].str.replace(
    r'[^0-9]', '', regex=True).astype(int)
df1 = df_z851
df2 = df_trkv_filtred

# 1. Filtra apenas passagens com medição não nula
df2_filtrado = df2[df2['max_valor'].notnull()].copy()

# 2. Ordena por equipamento e data (da mais recente para a mais antiga)
df2_filtrado = df2_filtrado.sort_values(
    ['key', 'timestr'], ascending=[True, True])

# ============================================================
# A) PEGAR A ÚLTIMA MEDIÇÃO E A DATA DA ÚLTIMA MEDIÇÃO
# ============================================================

# Ordena por data DESC dentro da chave
df2_desc = df2_filtrado.sort_values(
    ['key', 'timestr'], ascending=[True, False])

# Pega a última linha por equipamento
df_last = df2_desc.groupby('key').first().reset_index()

df_last.rename(columns={
    'max_valor': 'ultima_medicao',
    'timestr': 'data_ultima_medicao'
}, inplace=True)

# ============================================================
# B) PEGAR A MAIOR MEDIÇÃO ENTRE AS 3 ÚLTIMAS PASSAGENS
# ============================================================

# Pega rank das 3 últimas (já está ordenado ascendente)
df2_filtrado['rank'] = df2_filtrado.groupby(
    'key')['timestr'].rank(method='first', ascending=False)

df_top3 = df2_filtrado[df2_filtrado['rank'] <= 3]

df_max = df_top3.groupby('key')['max_valor'].max().reset_index()
df_max.rename(columns={'max_valor': 'max_medicao_ultimas_3'}, inplace=True)

# ============================================================
# C) MERGE FINAL
# ============================================================

df_final = df1.merge(df_max, on='key', how='left') \
    .merge(df_last[['key', 'ultima_medicao', 'data_ultima_medicao']],
            on='key', how='left')

# df_final = df_final[["EQUNR", "MODELO", "STATUS", "DATA_DE_FABRICACAO_trated", "DATA_GARANTIA_trated", "ULTIMA_RG",
#                      "KM_RODADO_DESDE_ULTIMA_RG", "max_medicao_ultimas_3", "ultima_medicao", "data_ultima_medicao", "key"]]

df_tratado = df_final.rename(columns={
    'max_medicao_ultimas_3': 'TRKV_max_medicao_ultimas_3',
    'ultima_medicao': 'TRKV_ultima_medicao',
    'data_ultima_medicao': 'TRKV_last_timestamp'
})

In [ ]:
8413916HFT

In [ ]:
df_filtrado = df_trkv_filtred[df_trkv_filtred["key"] == 8413916]
df_filtrado

In [ ]:
df_filtrado2 = df_trkv[df_trkv["CarIDNumber"] == 8413916]
df_filtrado2

In [22]:
df_trkv

,CarSequenceNumber,CarIDInitial,CarIDNumber,CarOrientation,CarType,TruckFields,TruckIDs,TruckValues,timestr,Header_TrainSequenceNumber_int,A#L_1,A#L_2,A#R_1,A#R_2,B#L_1,B#L_2,B#R_1,B#R_2,data_sincronizacao,concatenatedCarID
0,1,None,1.0,None,D,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#####N*Truck#####F*Truck#####N*Truck#####F,9#################*18#################*27#####...,29/09/2025 00:39:26,39467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-13 12:01:58.518,0000001nan
1,1,None,1.0,None,D,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#####N*Truck#####F*Truck#####N*Truck#####F,9#################*18#################*27#####...,29/09/2025 06:17:28,39476,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-13 12:01:58.518,0000001nan
2,1,None,1.0,None,D,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#####N*Truck#####F*Truck#####N*Truck#####F,9#################*18#################*27#####...,29/09/2025 12:44:29,39485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-13 12:01:58.518,0000001nan
3,1,None,1.0,None,D,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#####N*Truck#####F*Truck#####N*Truck#####F,9#################*18#################*27#####...,29/09/2025 14:47:27,39489,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-13 12:01:58.518,0000001nan
4,1,None,1.0,None,D,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#####N*Truck#####F*Truck#####N*Truck#####F,9#################*18#################*27#####...,29/09/2025 15:56:04,39490,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-13 12:01:58.518,0000001nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225241,38,TCT,8454787.0,A,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#A#R#4#2#N*Truck#A#L#4#2#F*Truck#B#R#2#1#...,0#####1#1######5#####*2############0#####*2###...,27/11/2025 08:38:54,41414,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-28 11:39:17.343,8454787TCT
225242,56,TCT,8454817.0,A,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#A#R#4#2#N*Truck#A#L#4#2#F*Truck#B#R#2#1#...,0#####1#1######5#####*2#################*2####...,26/11/2025 06:39:00,41377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-28 11:39:17.343,8454817TCT
225243,4,TCT,8454833.0,A,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#A#R#4#2#N*Truck#A#L#4#2#F*Truck#B#R#2#1#...,0#####1#1######5#####*0#####1#1######5#####*0#...,27/11/2025 08:38:54,41414,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-28 11:39:17.343,8454833TCT
225244,56,TCT,8454850.0,A,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#A#R#4#2#N*Truck#A#L#4#2#F*Truck#B#R#2#1#...,0#####1#1######5#####*0#####1#1######5#####*0#...,27/11/2025 08:38:54,41414,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-28 11:39:17.343,8454850TCT
225245,16,TCT,8454876.0,B,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#B#R#1#1#N*Truck#B#L#1#1#F*Truck#A#R#3#2#...,0#####1#1######5#####*0#####0#1######5#####*0#...,27/11/2025 11:17:19,41419,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-28 11:39:17.343,8454876TCT

In [ ]:
  # Garantir ordenação correta

def Trataroutliers_trkv(df_filtrado):
  df = df_filtrado.sort_values(["key", "timestr"])

  # Cálculo de min_3 e max_3 por key
  df["min_3"] = (
      df.groupby("key")["max_valor"]
        .rolling(window=3)
        .min()
        .shift(1)
        .reset_index(level=0, drop=True)
  )

  df["max_3"] = (
      df.groupby("key")["max_valor"]
        .rolling(window=3)
        .max()
        .shift(1)
        .reset_index(level=0, drop=True)
  )

  # Regras com tolerância de ±30%
  df["DESCARTAR"] = (
      (df["max_valor"] > df["max_3"] * 1.3) |   # 30% acima
      (df["max_valor"] < df["min_3"] * 0.7)     # 30% abaixo
  )

  # Coluna textual opcional
  df["STATUS"] = df["DESCARTAR"].map({True: "DESCARTAR", False: "OK"})
  df
  return df

In [23]:
df_trkv = df_trkv[df_trkv["CarIDNumber"]== 559652]
df_trkv

,CarSequenceNumber,CarIDInitial,CarIDNumber,CarOrientation,CarType,TruckFields,TruckIDs,TruckValues,timestr,Header_TrainSequenceNumber_int,A#L_1,A#L_2,A#R_1,A#R_2,B#L_1,B#L_2,B#R_1,B#R_2,data_sincronizacao,concatenatedCarID
116251,52,HFT,559652.0,A,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#####N*Truck#####F,#################*#################,04/10/2025 04:00:35,39601,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-13 12:01:58.518,0559652HFT
116252,33,HFT,559652.0,B,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#B#R#1#1#N*Truck#B#L#1#1#F*Truck#A#R#3#2#...,0#####0#0######3#####*2############0#####*2###...,08/10/2025 01:44:24,39774,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-13 12:01:58.518,0559652HFT
116253,32,HFT,559652.0,B,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#B#L#1#1#N*Truck#B#R#1#1#F*Truck#A#L#3#2#...,0#####0#0######2#####*2#################*2####...,12/10/2025 08:57:25,39935,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-13 12:01:58.518,0559652HFT
116254,22,HFT,559652.0,A,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#A#L#4#2#N*Truck#A#R#4#2#F*Truck#B#L#2#1#...,2############0#####*2#####0#0######3#####*4###...,16/10/2025 16:30:20,40113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-13 12:01:58.518,0559652HFT
116255,35,HFT,559652.0,B,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#B#L#1#1#N*Truck#B#R#1#1#F*Truck#A#L#3#2#...,0###2.056#2.261#0#0######4#####*0###2.392#1.92...,20/10/2025 19:45:45,40256,44.6278,45.5676,NaN,45.5676,52.2224,57.4294,60.7568,48.8950,2025-11-13 12:01:58.518,0559652HFT
116256,82,HFT,559652.0,A,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#A#L#4#2#N*Truck#A#R#4#2#F*Truck#B#L#2#1#...,2############0#####*2#####0#0######3#####*4###...,24/10/2025 08:32:38,40376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-13 12:01:58.518,0559652HFT
116257,103,HFT,559652.0,A,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#A#L#4#2#N*Truck#A#R#4#2#F*Truck#B#L#2#1#...,0#####0#0######3#####*0####1.047#0#0######3###...,05/09/2025 01:50:21,38708,NaN,NaN,NaN,26.5938,NaN,NaN,NaN,NaN,2025-11-13 12:01:58.518,0559652HFT
116258,102,HFT,559652.0,A,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#A#R#4#2#N*Truck#A#L#4#2#F*Truck#B#R#2#1#...,0###2.672#1.981#0#0##1.324####3#####*0###2.635...,08/09/2025 04:03:33,38819,66.9290,47.9298,67.8688,50.3174,51.2572,NaN,64.0842,47.4726,2025-11-13 12:01:58.518,0559652HFT
116259,83,HFT,559652.0,B,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#B#R#1#1#N*Truck#B#L#1#1#F*Truck#A#R#3#2#...,0#####0#0######3#####*2############0#####*2###...,13/09/2025 02:14:34,38971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-13 12:01:58.518,0559652HFT
116260,125,HFT,559652.0,B,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#B#L#1#1#N*Truck#B#R#1#1#F*Truck#A#L#3#2#...,0#####0#0######2#####*2############0#####*2###...,17/09/2025 08:28:19,39109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-13 12:01:58.518,0559652HFT
116261,77,HFT,559652.0,B,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#B#R#1#1#N*Truck#B#L#1#1#F*Truck#A#R#3#2#...,0#####0#0######3#####*2#################*2####...,21/09/2025 20:14:55,39248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-13 12:01:58.518,0559652HFT
116262,115,HFT,559652.0,B,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#B#L#1#1#N*Truck#B#R#1#1#F*Truck#A#L#3#2#...,0#####0#0######2#####*0#####0#0######3#####*0#...,25/09/2025 19:45:09,39371,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-13 12:01:58.518,0559652HFT
116263,56,HFT,559652.0,B,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#B#R#1#1#N*Truck#B#L#1#1#F*Truck#A#R#3#2#...,0#####0#0######3#####*2############0#####*2###...,02/11/2025 04:43:19,40675,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-13 12:01:58.518,0559652HFT
116264,136,HFT,559652.0,B,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#B#R#1#1#N*Truck#B#L#1#1#F*Truck#A#R#3#2#...,0#####0#0######3#####*2############0#####*2###...,10/11/2025 22:27:07,40968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-13 12:01:58.518,0559652HFT
116265,20,HFT,559652.0,A,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#####N*Truck#####F,#################*#################,18/11/2025 20:23:23,41137,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-22 11:41:50.573,0559652HFT
222565,125,HFT,559652.0,B,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#B#R#1#1#N*Truck#B#L#1#1#F*Truck#A#R#3#2#...,0#####0#0######3#####*2############0#####*2###...,27/11/2025 06:58:52,41411,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-28 11:39:17.343,0559652HFT

In [19]:
def tratar_trkv(df_trkv):

    # Usar data_sincronizacao pois timestr está vazio
    df_trkv['timestr'] = pd.to_datetime(
        df_trkv['data_sincronizacao'], errors='coerce'
    )

    df_trkv['Data'] = df_trkv['timestr'].dt.date

    colunas_impacto = [
        'A#L_1', 'A#L_2', 'A#R_1', 'A#R_2',
        'B#L_1', 'B#L_2', 'B#R_1', 'B#R_2'
    ]

    df_trkv[colunas_impacto] = df_trkv[colunas_impacto].replace(0, np.nan)

    df_trkv['Maior_Impacto_Linha'] = df_trkv[colunas_impacto].max(axis=1)

    df_trkv_max = (
        df_trkv.groupby('Data', as_index=False)['Maior_Impacto_Linha']
        .max()
        .rename(columns={'Maior_Impacto_Linha': 'Maior_Impacto_Diario'})
    )

    return df_trkv_max

In [20]:
df_trkv_trated = tratar_trkv(df_trkv)
df_trkv_trated

         Data  Maior_Impacto_Diario
0  2025-11-13               67.8688
1  2025-11-22                   NaN
2  2025-11-28                   NaN

In [ ]:

df_trkv['timestr'] = pd.to_datetime(
    df_trkv['timestr'], format='mixed', dayfirst=True, errors='coerce'
)
df_trkv['Data'] = df_trkv['timestr'].dt.date

# Colunas de impacto
colunas_impacto = ['A#L_1', 'A#L_2', 'A#R_1',
                    'A#R_2', 'B#L_1', 'B#L_2', 'B#R_1']

# Substituir valores 0 por NaN
df_trkv[colunas_impacto] = df_trkv[colunas_impacto].replace(
    0, np.nan)

# Calcular o maior valor por linha
df_trkv['Maior_Impacto_Linha'] = df_trkv[colunas_impacto].max(
    axis=1, skipna=True)

# Agrupar por data
df_trkv_max = (
    df_trkv.groupby('Data', as_index=False)['Maior_Impacto_Linha']
    .max()
    .rename(columns={'Maior_Impacto_Linha': 'Maior_Impacto_Diario'})
    .sort_values(by='Data', ascending=True)
)

# Formatar
df_trkv_max['TRKV_MAX_Cunha'] = df_trkv_max['Maior_Impacto_Diario'].round(
    2)
# df_trkv_max = tratar_outliers(df_trkv_max)
# print("-------------------------------------------------------df_trkv_max.head()")
# print(df_trkv_max.head())


df_trkv_max