In [2]:
import numpy as np
import plotly.express as px
import pandas as pd
from datetime import datetime
import re
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
import time
import streamlit as st
from pymongo import MongoClient
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

In [3]:
vg_entrada = "336700"
df_WCM, df_z369, df_trkv, df_z851, df_z1568 = busca_dados(vg_entrada)

NameError: name 'busca_dados' is not defined

In [ ]:
df_trkv

,CarSequenceNumber,CarIDInitial,CarIDNumber,CarOrientation,CarType,TruckFields,TruckIDs,TruckValues,timestr,Header_TrainSequenceNumber_int,A#L_1,A#L_2,A#R_1,A#R_2,B#L_1,B#L_2,B#R_1,B#R_2,data_sincronizacao,concatenatedCarID
0,49,HPT,336700.0,A,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#A#L#4#2#N*Truck#A#R#4#2#F*Truck#B#L#2#1#...,0###0.841#0.841#0#0######2#####*0###0.654#1.02...,01/10/2025 08:24:11,39540,21.3614,21.3614,16.6116,26.1112,20.8788,25.1460,20.8788,23.7236,2025-11-13 12:01:58.518,0336700HPT
1,97,HPT,336700.0,A,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#A#R#4#2#N*Truck#A#L#4#2#F*Truck#B#R#2#1#...,0###0.673#1.065#0#0######2#####*0###1.028#0.99...,06/10/2025 20:15:55,39725,26.1112,25.1460,17.0942,27.0510,27.0510,28.0162,23.2664,23.7236,2025-11-13 12:01:58.518,0336700HPT
2,76,HPT,336700.0,B,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#B#R#1#1#N*Truck#B#L#1#1#F*Truck#A#R#3#2#...,0#####0#0######2#####*2#################*2####...,10/10/2025 03:18:52,39846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-13 12:01:58.518,0336700HPT
3,35,HPT,336700.0,A,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#A#L#4#2#N*Truck#A#R#4#2#F*Truck#B#L#2#1#...,0###1.028#0.878#0#0######2#####*0###0.841#1.12...,19/10/2025 15:13:26,40220,26.1112,22.3012,21.3614,28.4734,26.1112,NaN,26.5938,25.1460,2025-11-13 12:01:58.518,0336700HPT
4,106,HPT,336700.0,A,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#A#L#4#2#N*Truck#A#R#4#2#F*Truck#B#L#2#1#...,0###0.822#0.804#0#0######2#####*0###0.729#0.89...,06/09/2025 13:35:24,38764,20.8788,20.4216,18.5166,22.7838,19.4564,25.6286,20.4216,22.3012,2025-11-13 12:01:58.518,0336700HPT
5,66,HPT,336700.0,A,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#A#L#4#2#N*Truck#A#R#4#2#F*Truck#B#L#2#1#...,0###0.822#0.822#0#0######2#####*0###0.710#0.97...,15/09/2025 08:01:39,39048,20.8788,20.8788,18.0340,24.6888,19.4564,25.1460,19.9390,23.7236,2025-11-13 12:01:58.518,0336700HPT
6,126,HPT,336700.0,B,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#B#L#1#1#N*Truck#B#R#1#1#F*Truck#A#L#3#2#...,0###1.009#1.009#0#0######2#####*0###0.990#0.99...,27/09/2025 06:37:34,39404,25.6286,21.8440,20.4216,28.0162,25.6286,25.6286,25.1460,25.1460,2025-11-13 12:01:58.518,0336700HPT
7,34,HPT,336700.0,B,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#B#L#1#1#N*Truck#B#R#1#1#F*Truck#A#L#3#2#...,0###1.047#1.028#0#0######2#####*0###1.028#0.99...,04/11/2025 17:38:16,40759,26.5938,21.3614,20.8788,29.4386,26.5938,26.1112,26.1112,25.1460,2025-11-13 12:01:58.518,0336700HPT

In [ ]:
def tratar_z369(df_z369):

    # df_z369['timestr'] = pd.to_datetime(df_z369['timestr'])
    # df_z369['Data'] = df_z369['timestr'].dt.date

    df_z369['Texto_Completo'] = (
        df_z369[['TEXTO', 'TEXTO AVARIA', 'TEXTO CAUSA']]
        .fillna('')  # substitui NaN por vazio
        .agg(' | '.join, axis=1)  # concatena linha a linha
        .str.strip(' | ')  # remove separador no fim se faltar campo
    )

    df_z369_trated = df_z369[['NOTA', 'ATIVO', 'TP NOTA', 'STATUS',
                                'dt_abertura_trated', 'dt_fechamento_trated', 'Texto_Completo']]
    
    df_timeline_z369 = df_z369_trated.copy()

    df_timeline_z369 = df_timeline_z369.rename(columns={
            "NOTA": "Evento",
            "TP NOTA": "Tipo_Evento",
            "dt_abertura_trated": "INICIO",
            "dt_fechamento_trated": "FIM"
        })


    return df_timeline_z369, df_z369_trated

df_timeline_z369, df_z369_trated = tratar_z369(df_z369)

In [ ]:
df_z1568

,Documento,ATIVO,DATA FIM,DATA INICIO,DATAREC,DISPONIBILIDADE,DT_HR_RET,ESCOPO,GRUPO_AVARIA,HORA FIM,...,RETENCAO,RET_INDEVIDA,SEQUENCIAL,STATUS,TEXTO,VAGAO,data_sincronizacao,dt_fim_trated,dt_inicio_trated,dt_modificacao
0,1689231,0336700HPT,20240607,20240415,20240415,DISPONIVEL,20240415045201,MC,TRUQUE,224856,...,DISPONIVEL,NÃO,0000000000,EM TRAB.,ZRO:(MC PMV)CAB A E B ANEL DO PRATO AVARIADO +...,0336700,2025-11-12 18:08:30.712,2024-06-07,2024-04-15,2024-06-07 22:49:06
1,1761739,0336700HPT,20250826,20250814,20250810,DISPONIVEL,20250814134600,RA,REVISÃO,231048,...,DISPONIVEL,NÃO,0000178476,EM TRAB.,ZRO:(MP T9)REVISÃO RA +|3E RIDE CONTROL+INSPEÇ...,0336700,2025-11-12 18:08:30.712,2025-08-26,2025-08-14,2025-08-26 23:10:53

In [ ]:
def inserir_z1568(df_z1568):

    # df_z1568['timestr'] = pd.to_datetime(df_z1568['timestr'])
    # df_z1568['Data'] = df_z1568['timestr'].dt.date

    df_z1568['Texto_Completo'] = (
        df_z1568[['PMV', 'STATUS', 'GRUPO_AVARIA', 'TEXTO']]
        .fillna('')  # substitui NaN por vazio
        .agg(' | '.join, axis=1)  # concatena linha a linha
        .str.strip(' | ')  # remove separador no fim se faltar campo
    )

    df_z1568_trated = df_z1568[['Documento', 'ATIVO', 'ID_Manutecao', 'STATUS',
                                'dt_inicio_trated', 'dt_fim_trated', 'Texto_Completo','ID_Manutecao']]
    
    df_timeline_z1568 = df_z1568_trated.copy()

    df_timeline_z1568 = df_timeline_z1568.rename(columns={
            "NOTA": "Evento",
            "ID_Manutecao": "Tipo_Evento",
            "dt_inicio_trated": "INICIO",
            "dt_fim_trated": "FIM"
        })


    return df_timeline_z1568

df_timeline_z1568 = inserir_z1568(df_z1568)

KeyError: "['TP NOTA'] not in index"

In [ ]:
df_trkv_trated

In [ ]:
from pymongo import MongoClient
from datetime import datetime

client = MongoClient("mongodb+srv://int_dados:e7bUe2bXbKDu3Xzr@rumo-dev2.hbdcrld.mongodb.net/?authSource=admin")
db = client["supervisorio"]
collection = db["base_last_update"]

def update_last_sync(base_name: str):
    """
    Atualiza a data de sincronização de uma base.
    
    Params:
        base_name (str): Nome da base a atualizar.
        
    Efetua upsert: se não existir, cria.
    """
    now = datetime.now()

    result = collection.update_one(
        {"base": base_name},
        {"$set": {"last_update": now}},
        upsert=True
    )

    print(f"✔ Atualizado: {base_name} → {now}")
    return result

In [ ]:
from pymongo import MongoClient
import pandas as pd

# ==============================
# 1. Conexão com o MongoDB
# ==============================
client = MongoClient(
    "mongodb+srv://int_dados:e7bUe2bXbKDu3Xzr@rumo-dev2.hbdcrld.mongodb.net/?authSource=admin"
)

db = client["supervisorio"]
collection = db["resumo_vagoes"]

# ==============================
# 2. Buscar todos os registros
# ==============================
cursor = collection.find({})
data = list(cursor)

# Garantir que há registros
if not data:
    print("⚠️ Nenhum dado encontrado no MongoDB.")
else:
    print(f"Registros carregados: {len(data)}")

# ==============================
# 3. Converter em DataFrame
# ==============================
df = pd.DataFrame(data)

# Remover o campo _id (opcional)
if "_id" in df.columns:
    df.drop(columns=["_id"], inplace=True)

print(df.head())

# ==============================
# 4. Salvar em Parquet
# ==============================
output_path = r"temp\df_zCadVagoes_resumos.parquet"
df.to_parquet(output_path, index=False, engine="pyarrow")
print(f"Arquivo salvo em: {output_path}")

c:\Users\leona\anaconda3\Lib\site-packages\pymongo\pyopenssl_context.py:352: CryptographyDeprecationWarning: Parsed a negative serial number, which is disallowed by RFC 5280. Loading this certificate will cause an exception in the next release of cryptography.
  _crypto.X509.from_cryptography(x509.load_der_x509_certificate(cert))

KeyboardInterrupt:

In [ ]:
MONGO_URI = "mongodb+srv://int_dados:e7bUe2bXbKDu3Xzr@rumo-dev2.hbdcrld.mongodb.net/?authSource=admin"
DB_NAME = "supervisorio"

In [3]:
import streamlit as st
from pymongo import MongoClient
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime
import re
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
import warnings
warnings.filterwarnings("ignore")

In [ ]:
def busca_dados(vagao):
    def busca_z1568(vagao):
        # Conexão com o MongoDB
        vagao = int(vagao)
        client = MongoClient(
            MONGO_URI)

        # Definição do filtro
        filter = {}

        # Consulta
        cursor = client[DB_NAME]['z1568_Liberacoes_Retencoes_full'].find(
            filter)

        # Converter o cursor em lista e depois em DataFrame
        df = pd.DataFrame(list(cursor))

        # (Opcional) Remover a coluna _id, se não for necessária
        if '_id' in df.columns:
            df.drop('_id', axis=1, inplace=True)

        return df

    def busca_z851(vagao):
        # Conexão com o MongoDB
        vagao = int(vagao)
        client = MongoClient(
            MONGO_URI)

        # Definição do filtro
        filter = {}

        # Consulta
        cursor = client[DB_NAME]['CadastroVagoes_full'].find(filter)

        # Converter o cursor em lista e depois em DataFrame
        df = pd.DataFrame(list(cursor))

        # (Opcional) Remover a coluna _id, se não for necessária
        if '_id' in df.columns:
            df.drop('_id', axis=1, inplace=True)

        return df

    def busca_wcm(vagao):
        # Conexão com o MongoDB
        client = MongoClient(
            MONGO_URI)
        vagao_str = str(vagao)
        # Pipeline de agregação
        pipeline = [
            {
                '$match': {
                    'json_documents.json_Identificação do veículo': { '$ne': "" }
                }
            },
            {
                '$project': {
                    'json_documents': 1,
                    '_id': 0
                }
            },
            {
                '$unwind': '$json_documents'
            },
            {
                '$match': {
                    'json_documents.json_Identificação do veículo': { '$ne': "" }
                }
            }
        ]


        # Executa a agregação
        result = client[DB_NAME]['WCM'].aggregate(pipeline)

        # Converte o resultado em DataFrame
        df = pd.DataFrame(list(result))

        # Se quiser expandir o dicionário 'json_documents' em colunas separadas:
        if not df.empty and 'json_documents' in df.columns:
            df = pd.json_normalize(df['json_documents'])

        return df

    def busca_z369(vagao):
        # Conexão com o MongoDB
        client = MongoClient(
            MONGO_URI)

        vagao_str = str(vagao)

        # Definição do filtro
        filter = {"STATUS": "MSPN"}

        # Consulta
        cursor = client[DB_NAME]['z369_trated'].find(filter)

        # Converter o cursor em lista e depois em DataFrame
        df = pd.DataFrame(list(cursor))

        # (Opcional) Remover a coluna _id, se não for necessária
        if '_id' in df.columns:
            df.drop('_id', axis=1, inplace=True)

        return df

    def busca_TRKV(vagao):
        # Conexão com o MongoDB
        vagao = int(vagao)
        client = MongoClient(
            MONGO_URI)

        # Definição do filtro
        filter = { 'CarIDNumber': { '$ne': 0 } }
        #filter = { }

        # Consulta
        cursor = client[DB_NAME]['TRKV_treated'].find(filter)

        # Converter o cursor em lista e depois em DataFrame
        df = pd.DataFrame(list(cursor))

        # (Opcional) Remover a coluna _id, se não for necessária
        if '_id' in df.columns:
            df.drop('_id', axis=1, inplace=True)

        return df

    def busca_Tela164(vagao):
        from pymongo import MongoClient
        import pandas as pd

        # Garantir que o vagao é string (Mongo armazena como string)
        vagao = str(vagao)

        # Conexão com o MongoDB
        client = MongoClient(MONGO_URI)

        # Filtro usando o parâmetro recebido
        filter_query = {}

        # Consulta com limit = 1
        cursor = client[DB_NAME]['tela164_full'].find(filter_query, limit=1)

        # Converter cursor para DataFrame
        df = pd.DataFrame(list(cursor))

        # Remover coluna _id se existir
        if '_id' in df.columns:
            df.drop('_id', axis=1, inplace=True)

        return df

    def busca_SAT_TAREFAS_full(vagao):
        from pymongo import MongoClient
        import pandas as pd

        # Garantir que o vagao é string (Mongo armazena como string)
        vagao = str(vagao)

        # Conexão com o MongoDB
        client = MongoClient(MONGO_URI)

        # Filtro usando o parâmetro recebido
        filter_query = {'EQUNR': re.compile(f"{vagao}")}

        # Consulta com limit = 1
        cursor = client[DB_NAME]['SAT_TAREFAS_full'].find(
            filter_query)

        # Converter cursor para DataFrame
        df = pd.DataFrame(list(cursor))

        # Remover coluna _id se existir
        if '_id' in df.columns:
            df.drop('_id', axis=1, inplace=True)

        return df

    def medir_tempo(func, *args, **kwargs):
        inicio = time.time()
        resultado = func(*args, **kwargs)
        fim = time.time()
        print(f"{func.__name__} executou em {fim - inicio:.2f} segundos")
        return resultado

    def exec_parallel(vagao):
        funcoes = [
            busca_wcm,
            busca_z369,
            busca_TRKV,
            busca_z851,
            busca_z1568,
            busca_Tela164
        ]

        resultados = {}

        with ThreadPoolExecutor(max_workers=5) as executor:
            futures = {
                executor.submit(medir_tempo, f, vagao): f.__name__
                for f in funcoes
            }

            for future in as_completed(futures):
                nome = futures[future]
                try:
                    resultados[nome] = future.result()
                except Exception as e:
                    print(f"Erro na função {nome}: {e}")
                    resultados[nome] = None

        return resultados

    result = exec_parallel(vagao)

    df_WCM = result["busca_wcm"]
    df_z369 = result["busca_z369"]
    df_trkv = result["busca_TRKV"]
    df_z851 = result["busca_z851"]
    df_z1568 = result["busca_z1568"]
    df_164 = result["busca_Tela164"]
    #

    print(len(df_WCM))
    print(len(df_z369))
    print(len(df_trkv))
    print(len(df_z851))
    print(len(df_z1568))
    print(len(df_164))
    
    st.success("Função executada com sucesso!")

    return df_WCM, df_z369, df_trkv, df_z851, df_z1568, df_164

In [ ]:
df_WCM, df_z369, df_trkv, df_z851, df_z1568, df_164 = busca_dados(0)
print(df_WCM.shape, df_z369.shape, df_trkv.shape, df_z851.shape, df_z1568.shape, df_164.shape)

c:\Users\leona\anaconda3\Lib\site-packages\pymongo\pyopenssl_context.py:352: CryptographyDeprecationWarning: Parsed a negative serial number, which is disallowed by RFC 5280. Loading this certificate will cause an exception in the next release of cryptography.
  _crypto.X509.from_cryptography(x509.load_der_x509_certificate(cert))

busca_wcm executou em 9.09 segundos
busca_z851 executou em 13.47 segundos
busca_z369 executou em 14.15 segundos

c:\Users\leona\anaconda3\Lib\site-packages\pymongo\pyopenssl_context.py:352: CryptographyDeprecationWarning: Parsed a negative serial number, which is disallowed by RFC 5280. Loading this certificate will cause an exception in the next release of cryptography.
  _crypto.X509.from_cryptography(x509.load_der_x509_certificate(cert))

busca_Tela164 executou em 7.23 segundos
busca_z1568 executou em 24.56 segundos
busca_TRKV executou em 82.58 segundos
3708
20804
245766
14636
32109
1

In [12]:
import pandas as pd

def salvar_parquet(df, path):
    df.to_parquet(path, index=False, engine="pyarrow")

In [13]:
import asyncio
from concurrent.futures import ThreadPoolExecutor
import pandas as pd
import os


def salvar_parquet(df, path):
    # garante que a pasta existe
    os.makedirs(os.path.dirname(path), exist_ok=True)
    df.to_parquet(path, index=False, engine="pyarrow")


async def salvar_tudo_assincrono(dfs, paths):
    loop = asyncio.get_event_loop()

    with ThreadPoolExecutor() as executor:
        tarefas = [
            loop.run_in_executor(executor, salvar_parquet, df, path)
            for df, path in zip(dfs, paths)
        ]

        await asyncio.gather(*tarefas)

def inserir_wcm_hist(df_wcm_trated):
    df_wcm_trated_histgeral = df_wcm_trated.copy()
    print(df_wcm_trated)
    # 1) Garantir datetime (com hora) na coluna Data
    df_wcm_trated_histgeral['INICIO'] = pd.to_datetime(
        df_wcm_trated_histgeral['Data'])
    df_wcm_trated_histgeral['Tipo_Evento'] = "Passagem wcm"
    # + \            df_wcm_trated_histgeral['Data'].astype(str)
    df_wcm_trated_histgeral['Evento'] = "wcm"

    df_wcm_trated_histgeral['Texto_Completo'] = "Maior_Impacto_kN = " + \
        df_wcm_trated_histgeral['Maior_Impacto_kN'].astype(str)

    df_wcm_trated_histgeral["Data"] = pd.to_datetime(
        df_wcm_trated_histgeral["Data"], format="%Y-%m-%d %H:%M")
    df_wcm_trated_histgeral["FIM"] = (
        df_wcm_trated_histgeral["Data"] + pd.to_timedelta(12, unit="h")
    )
    df_wcm_trated_histgeral['Tipo_Evento'] = "WCM"

    df_wcm_total = df_wcm_trated_histgeral[[
        'Evento', 'INICIO', 'FIM', 'Texto_Completo', 'Tipo_Evento']]

    return df_wcm_total

In [93]:
df_164   = pd.read_parquet("temp/df_164.parquet")
df_trkv  = pd.read_parquet("temp/df_trkv.parquet")
df_WCM   = pd.read_parquet("temp/df_WCM.parquet")
df_z369  = pd.read_parquet("temp/df_z369.parquet")
df_z851  = pd.read_parquet("temp/df_z851.parquet")
df_z1568 = pd.read_parquet("temp/df_z1568.parquet")

In [95]:
df_z851

,EQUNR,Atualizacao,BITOLA,DATA_DE_FABRICACAO,DATA_DE_FABRICACAO_trated,DATA_FIM,DATA_FIM_trated,DATA_GARANTIA,DATA_GARANTIA_trated,ELIMINADO,KM_RODADO_DESDE_ULTIMA_RG,MALHA,MODELO,STATUS,ULTIMA_RG,ULTIMA_RI,ULTIMA_RR,data_sincronizacao,dt_last_udate_trated
0,3502520PNQ,2025-11-18 07:49:42.337,L,20100305,2010-03-05,99991231,None,00000000,NaT,,78104.150,N,PLATAF. VP,1,2010-04-21,2010-04-21,2010-04-21,2025-11-18 09:23:59.586,2025-11-18 07:49:42.337
1,8418497HFT,2025-11-18 07:49:42.337,L,20061006,2006-10-06,99991231,None,20290807,2029-08-07,,155716.585,N,GRANELEIROS,1,2024-08-08,2024-08-08,2024-08-08,2025-11-18 09:23:59.586,2025-11-18 07:49:42.337
2,8421200HFT,2025-11-18 07:49:42.337,L,20061006,2006-10-06,99991231,None,20300513,2030-05-13,,63865.552,N,GRANELEIROS,1,2025-05-14,2025-05-14,2025-05-14,2025-11-18 09:23:59.586,2025-11-18 07:49:42.337
3,8423563HFT,2025-11-18 07:49:42.337,L,20061006,2006-10-06,99991231,None,20220204,2022-02-04,,724792.741,N,GRANELEIROS,1,2003-04-19,2019-02-05,2019-02-05,2025-11-18 09:23:59.586,2025-11-18 07:49:42.337
4,6274358HNR,2025-11-18 07:49:42.337,L,20100309,2010-03-09,99991231,None,00000000,NaT,,79492.020,N,GÔNDOLAS VP,1,2010-03-11,2010-03-11,2010-03-11,2025-11-18 09:23:59.586,2025-11-18 07:49:42.337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14631,0554162HFT,2025-11-18 07:49:42.337,L,20110125,2011-01-25,99991231,None,20250503,2025-05-03,,412650.072,N,GRANELEIROS,1,2006-01-26,2022-05-04,2022-05-04,2025-11-18 09:23:59.586,2025-11-18 07:49:42.337
14632,0554103HFT,2025-11-18 07:49:42.337,L,20110125,2011-01-25,99991231,None,20221114,2022-11-14,,1466701.199,N,GRANELEIROS,1,2006-01-26,2019-11-15,2011-01-25,2025-11-18 09:23:59.586,2025-11-18 07:49:42.337
14633,0532363TCT,2025-11-18 07:49:42.337,L,20080314,2008-03-14,00000000,None,20250324,2025-03-24,,321972.736,N,TANQUES,1,2003-03-16,2022-03-25,2022-03-25,2025-11-18 09:23:59.586,2025-11-18 07:49:42.337
14634,0533459TCT,2025-11-18 07:49:42.337,L,20080509,2008-05-09,00000000,None,20260719,2026-07-19,,199835.095,N,TANQUES,1,2010-04-11,2023-07-20,2023-07-20,2025-11-18 09:23:59.586,2025-11-18 07:49:42.337
14635,0978779HFT,2025-11-18 07:49:42.337,L,20070503,2007-05-03,99991231,None,20241005,2024-10-05,,400183.867,N,GRANELEIROS,1,2010-06-16,2021-10-06,2021-10-06,2025-11-18 09:23:59.586,2025-11-18 07:49:42.337

In [ ]:
# Conversões sem alterar as colunas originais
dt_164     = pd.to_datetime(df_164['DT_CARGA'], errors='coerce')
dt_trkv    = pd.to_datetime(df_trkv['data_sincronizacao'], errors='coerce')
dt_WCM     = pd.to_datetime(df_WCM['json_trem_TrainTime'], errors='coerce')
dt_z369    = pd.to_datetime(df_z369['dt_last_udate_trated'], errors='coerce')
dt_z851    = pd.to_datetime(df_z851['Atualizacao'], errors='coerce')
dt_z1568   = pd.to_datetime(df_z1568['dt_fim_trated'], errors='coerce')

# Datas mais recentes
data_mais_recente_164   = dt_164.max()
data_mais_recente_trkv  = dt_trkv.max()
data_mais_recente_WCM   = dt_WCM.max()
data_mais_recente_z369  = dt_z369.max()
data_mais_recente_z851  = dt_z851.max()
data_mais_recente_z1568 = dt_z1568.max()

print("164:", data_mais_recente_164)
print("TRKV:", data_mais_recente_trkv)
print("WCM:", data_mais_recente_WCM)
print("Z369:", data_mais_recente_z369)
print("Z851:", data_mais_recente_z851)
print("Z1568:", data_mais_recente_z1568)

164: 2025-11-28 08:14:17
TRKV: 2025-11-26 11:39:19.032000
WCM: 2025-11-27 06:58:38
Z369: 2025-11-27 00:00:00
Z851: 2025-11-18 07:49:42.337000
Z1568: 2025-11-27 00:00:00

Timestamp('2025-11-27 00:00:00')

In [71]:
df_trkv['timestr'] = pd.to_datetime(
    df_trkv['timestr'],
    format="%d/%m/%Y %H:%M:%S",
    errors='coerce'
)

data_mais_recente = df_trkv['timestr'].max()
print(data_mais_recente)

2025-12-10 22:39:58

df_WCM['json_trem_TrainTime'] = pd.to_datetime(
    df_WCM['json_trem_TrainTime'],
    errors='coerce'
)

data_mais_recente = df_WCM['json_trem_TrainTime'].max()
print(data_mais_recente)

In [16]:
df_z851

,EQUNR,Atualizacao,BITOLA,DATA_DE_FABRICACAO,DATA_DE_FABRICACAO_trated,DATA_FIM,DATA_FIM_trated,DATA_GARANTIA,DATA_GARANTIA_trated,ELIMINADO,KM_RODADO_DESDE_ULTIMA_RG,MALHA,MODELO,STATUS,ULTIMA_RG,ULTIMA_RI,ULTIMA_RR,data_sincronizacao,dt_last_udate_trated
0,3502520PNQ,2025-11-18 07:49:42.337,L,20100305,2010-03-05,99991231,None,00000000,NaT,,78104.150,N,PLATAF. VP,1,2010-04-21,2010-04-21,2010-04-21,2025-11-18 09:23:59.586,2025-11-18 07:49:42.337
1,8418497HFT,2025-11-18 07:49:42.337,L,20061006,2006-10-06,99991231,None,20290807,2029-08-07,,155716.585,N,GRANELEIROS,1,2024-08-08,2024-08-08,2024-08-08,2025-11-18 09:23:59.586,2025-11-18 07:49:42.337
2,8421200HFT,2025-11-18 07:49:42.337,L,20061006,2006-10-06,99991231,None,20300513,2030-05-13,,63865.552,N,GRANELEIROS,1,2025-05-14,2025-05-14,2025-05-14,2025-11-18 09:23:59.586,2025-11-18 07:49:42.337
3,8423563HFT,2025-11-18 07:49:42.337,L,20061006,2006-10-06,99991231,None,20220204,2022-02-04,,724792.741,N,GRANELEIROS,1,2003-04-19,2019-02-05,2019-02-05,2025-11-18 09:23:59.586,2025-11-18 07:49:42.337
4,6274358HNR,2025-11-18 07:49:42.337,L,20100309,2010-03-09,99991231,None,00000000,NaT,,79492.020,N,GÔNDOLAS VP,1,2010-03-11,2010-03-11,2010-03-11,2025-11-18 09:23:59.586,2025-11-18 07:49:42.337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14631,0554162HFT,2025-11-18 07:49:42.337,L,20110125,2011-01-25,99991231,None,20250503,2025-05-03,,412650.072,N,GRANELEIROS,1,2006-01-26,2022-05-04,2022-05-04,2025-11-18 09:23:59.586,2025-11-18 07:49:42.337
14632,0554103HFT,2025-11-18 07:49:42.337,L,20110125,2011-01-25,99991231,None,20221114,2022-11-14,,1466701.199,N,GRANELEIROS,1,2006-01-26,2019-11-15,2011-01-25,2025-11-18 09:23:59.586,2025-11-18 07:49:42.337
14633,0532363TCT,2025-11-18 07:49:42.337,L,20080314,2008-03-14,00000000,None,20250324,2025-03-24,,321972.736,N,TANQUES,1,2003-03-16,2022-03-25,2022-03-25,2025-11-18 09:23:59.586,2025-11-18 07:49:42.337
14634,0533459TCT,2025-11-18 07:49:42.337,L,20080509,2008-05-09,00000000,None,20260719,2026-07-19,,199835.095,N,TANQUES,1,2010-04-11,2023-07-20,2023-07-20,2025-11-18 09:23:59.586,2025-11-18 07:49:42.337
14635,0978779HFT,2025-11-18 07:49:42.337,L,20070503,2007-05-03,99991231,None,20241005,2024-10-05,,400183.867,N,GRANELEIROS,1,2010-06-16,2021-10-06,2021-10-06,2025-11-18 09:23:59.586,2025-11-18 07:49:42.337

In [ ]:
# ============================================================
# BUSCAR DADOS TELA 164 → SALVAR PARQUET → LIMPAR MONGO → INSERIR NO MONGO
# ============================================================

print("┌───────────────────────────────────────────────┐")
print("│               STAGE to Mongo                  │")
print("│   Projeto IA Vagões     Translogic            │")
print("└───────────────────────────────────────────────┘\n")

import pandas as pd
from pymongo import MongoClient
import pyodbc
import warnings

warnings.filterwarnings("ignore")


# ============================================================
# CONFIGURAÇÕES
# ============================================================
SQL_DRIVER = "{SQL Server}"
SQL_SERVER = "10.200.92.45"
SQL_DATABASE = "ALL_STAGE"

MONGO_URI = "mongodb+srv://int_dados:e7bUe2bXbKDu3Xzr@rumo-dev2.hbdcrld.mongodb.net/?authSource=admin"
MONGO_DB = "supervisorio"
MONGO_COLLECTION = "CadastroVagoes_full"

PARQUET_PATH = r"C:\src_Rumo\script\exerumo\Scripts_On\STAGE_to_Mongo\df_CadastroVagoes_full.parquet"


# ============================================================
# 1. BUSCAR REGISTROS DO SQL E SALVAR PARQUET
# ============================================================
def buscar_registros_sql():
    CONN = pyodbc.connect(
        driver=SQL_DRIVER,
        server=SQL_SERVER,
        database=SQL_DATABASE,
        Trusted_Connection="yes"
    )

    QUERY = """
        SELECT
            --MANDT,
            Z71.EQUNR,
            Z71.DATA_INI AS 'DATA_DE_FABRICACAO',
            Z71.DATA_FIM,
            Z71.MODELO,
            Z71.STATUS,
            Z71.ELIMINADO,
            Z71.MALHA,
            Z71.BITOLA,
            Z71.DATA_GARANTIA,
            PCMRG.[ult RG] AS 'ULTIMA_RG',
                PCMRG.[ult RR] AS 'ULTIMA_RR',
            PCMRI.[ult IK]AS 'ULTIMA_RI',
            PCMRG.km_rodado AS 'KM_RODADO_DESDE_ULTIMA_RG',
            PCMRG.Atualizacao
        FROM ALL_STAGE.SAP.ZPMT0071 Z71 (NOLOCK)
        LEFT JOIN ALL_STAGE.pcm.TB_KM_RG_NORTE PCMRG (NOLOCK) ON Z71.EQUNR = PCMRG.EQUNR 
        LEFT JOIN ALL_STAGE.pcm.TB_KM_RI_NORTE PCMRI (NOLOCK) ON Z71.EQUNR = PCMRI.EQUNR
        LEFT JOIN ALL_STAGE.SAP.ZPMT0404 ZPMT0404 (NOLOCK) ON Z71.EQUNR = ZPMT0404.EQUNR
        WHERE 1=1
        --AND STATUS IN ('1','2')
        AND BITOLA ='L'
        --AND Z71.ELIMINADO <> 'X'
        --AND Z71.EQUNR ='0556246HFT'     
    """

    df = pd.read_sql_query(QUERY, CONN)
    df.to_parquet(PARQUET_PATH, index=False, engine="pyarrow")

    print(f"[SQL] Dados carregados: {df.shape}")
    return df


# ============================================================
# 2. APAGAR DOCUMENTOS DA COLLECTION NO MONGO
# ============================================================
def apagar_todos_registros():
    client = MongoClient(MONGO_URI)
    coll = client[MONGO_DB][MONGO_COLLECTION]
    res = coll.delete_many({})
    print(f"[Mongo] Registros apagados: {res.deleted_count}")


# ============================================================
# 3. LER PARQUET
# ============================================================
def ler_parquet(caminho):
    df = pd.read_parquet(caminho, engine="pyarrow")
    print(f"[Parquet] DF carregado: {df.shape}")
    return df


# ============================================================
# 4. INSERIR DF NO MONGO (SEM ERRO DE NaT / TIMEZONE)
# ============================================================
def inserir_df_mongo(df, batch_size=1500):
    client = MongoClient(MONGO_URI)
    coll = client[MONGO_DB][MONGO_COLLECTION]

    # Remover NaN -> None
    df = df.where(pd.notnull(df), None)

    # Converter QUALQUER datetime para string ISO sem timezone
    for col in df.columns:
        if "datetime64" in str(df[col].dtype):
            df[col] = df[col].apply(
                lambda x: x.strftime("%Y-%m-%d %H:%M:%S") if pd.notnull(x) else None
            )

    # Inserção em batches
    total = 0
    for ini in range(0, len(df), batch_size):
        batch = df.iloc[ini: ini + batch_size].to_dict("records")
        result = coll.insert_many(batch)
        total += len(result.inserted_ids)
        print(f"[Mongo] Batch inserido: {len(result.inserted_ids)}")

    print(f"[Mongo] Total inserido em {MONGO_COLLECTION}: {total}")


# ============================================================
# 5. PIPELINE COMPLETO
# ============================================================
if __name__ == "__main__":
    print("==== INICIANDO PROCESSO ====")

    print("\n1) Buscando registros SQL...")
    buscar_registros_sql()

    print("\n2) Apagando registros do Mongo...")
    apagar_todos_registros()

    print("\n3) Carregando Parquet...")
    df_parquet = ler_parquet(PARQUET_PATH)

    print("\n4) Inserindo no Mongo...")
    inserir_df_mongo(df_parquet)

    print("\n==== PROCESSO FINALIZADO ====")

In [ ]:
import pandas as pd


def concatenar_dados_trkv_z851(df_z851, df_trkv):
    df_trkv["max_valor"] = df_trkv[["A#L_1", "A#L_2", "A#R_1", "A#R_2","B#L_1","B#L_2","B#R_1","B#R_2"]].max(axis=1)
    df_trkv_filtred = df_trkv[["CarIDInitial","CarIDNumber","timestr","max_valor"]]

    df_trkv_filtred = df_trkv_filtred[df_trkv_filtred["CarIDInitial"].notna()]
    df_trkv_filtred = df_trkv_filtred[df_trkv_filtred["max_valor"].notna()]
    df_trkv_filtred['timestr'] = pd.to_datetime(df_trkv_filtred['timestr'], format="%d/%m/%Y %H:%M:%S", errors='coerce')
    df_trkv_filtred['key'] = df_trkv_filtred['CarIDNumber'].astype(int)

    df_z851['key'] = df_z851['EQUNR'].str.replace(r'[^0-9]', '', regex=True).astype(int)
    df1 = df_z851
    df2 = df_trkv_filtred

    # 1. Filtra apenas passagens com medição não nula
    df2_filtrado = df2[df2['max_valor'].notnull()].copy()

    # 2. Ordena por equipamento e data (da mais recente para a mais antiga)
    df2_filtrado = df2_filtrado.sort_values(['key', 'timestr'], ascending=[True, True])

    # ============================================================
    # A) PEGAR A ÚLTIMA MEDIÇÃO E A DATA DA ÚLTIMA MEDIÇÃO
    # ============================================================

    # Ordena por data DESC dentro da chave
    df2_desc = df2_filtrado.sort_values(['key', 'timestr'], ascending=[True, False])

    # Pega a última linha por equipamento
    df_last = df2_desc.groupby('key').first().reset_index()

    df_last.rename(columns={
        'max_valor': 'ultima_medicao',
        'timestr': 'data_ultima_medicao'
    }, inplace=True)

    # ============================================================
    # B) PEGAR A MAIOR MEDIÇÃO ENTRE AS 3 ÚLTIMAS PASSAGENS
    # ============================================================

    # Pega rank das 3 últimas (já está ordenado ascendente)
    df2_filtrado['rank'] = df2_filtrado.groupby('key')['timestr'].rank(method='first', ascending=False)

    df_top3 = df2_filtrado[df2_filtrado['rank'] <= 3]

    df_max = df_top3.groupby('key')['max_valor'].max().reset_index()
    df_max.rename(columns={'max_valor': 'max_medicao_ultimas_3'}, inplace=True)

    # ============================================================
    # C) MERGE FINAL
    # ============================================================

    df_final = df1.merge(df_max, on='key', how='left') \
                .merge(df_last[['key', 'ultima_medicao', 'data_ultima_medicao']], 
                        on='key', how='left')

    df_final = df_final[["EQUNR","MODELO","STATUS","DATA_DE_FABRICACAO_trated","DATA_GARANTIA_trated","ULTIMA_RG","KM_RODADO_DESDE_ULTIMA_RG","max_medicao_ultimas_3","ultima_medicao","data_ultima_medicao","key"]]

    df_tratado = df_final.rename(columns={
        'max_medicao_ultimas_3' : 'TRKV_max_medicao_ultimas_3',
        'ultima_medicao': 'TRKV_ultima_medicao',
        'data_ultima_medicao': 'TRKV_last_timestamp'
    })

    return df_tratado

df_new1 = concatenar_dados_trkv_z851(df_z851, df_trkv)
df_new1

,EQUNR,MODELO,STATUS,DATA_DE_FABRICACAO_trated,DATA_GARANTIA_trated,ULTIMA_RG,KM_RODADO_DESDE_ULTIMA_RG,TRKV_max_medicao_ultimas_3,TRKV_ultima_medicao,TRKV_last_timestamp,key
0,3502520PNQ,PLATAF. VP,1,2010-03-05,NaT,2010-04-21,78104.150,NaN,NaN,NaT,3502520
1,8418497HFT,GRANELEIROS,1,2006-10-06,2029-08-07,2024-08-08,155716.585,29.4386,29.4386,2025-11-19 02:45:37,8418497
2,8421200HFT,GRANELEIROS,1,2006-10-06,2030-05-13,2025-05-14,63865.552,26.5938,26.5938,2025-11-24 14:33:35,8421200
3,8423563HFT,GRANELEIROS,1,2006-10-06,2022-02-04,2003-04-19,724792.741,34.6456,34.6456,2025-10-13 19:15:35,8423563
4,6274358HNR,GÔNDOLAS VP,1,2010-03-09,NaT,2010-03-11,79492.020,NaN,NaN,NaT,6274358
...,...,...,...,...,...,...,...,...,...,...,...
14631,0554162HFT,GRANELEIROS,1,2011-01-25,2025-05-03,2006-01-26,412650.072,35.6108,33.2232,2025-11-08 16:35:24,554162
14632,0554103HFT,GRANELEIROS,1,2011-01-25,2022-11-14,2006-01-26,1466701.199,39.8780,39.8780,2025-11-06 09:44:16,554103
14633,0532363TCT,TANQUES,1,2008-03-14,2025-03-24,2003-03-16,321972.736,30.3784,29.4386,2025-11-22 08:13:19,532363
14634,0533459TCT,TANQUES,1,2008-05-09,2026-07-19,2010-04-11,199835.095,29.8958,29.8958,2025-11-18 10:20:14,533459
14635,0978779HFT,GRANELEIROS,1,2007-05-03,2024-10-05,2010-06-16,400183.867,60.2742,60.2742,2025-11-13 03:21:54,978779

In [60]:
def tratar_WCM(df_WCM):

    # Garantir datetime
    df_WCM['json_trem_TrainTime'] = pd.to_datetime(
        df_WCM['json_trem_TrainTime'], errors='coerce'
    )

    # Criar coluna somente com a data
    df_WCM['Data'] = df_WCM['json_trem_TrainTime'].dt.date

    # Agrupamento por veículo + data
    df_WCM_max = (
        df_WCM.groupby(
            ['json_Identificação do veículo', 'Data'], 
            as_index=False
        )['json_Força de pico de impacto da roda (kN)']
        .max()
        .rename(columns={
            'json_Força de pico de impacto da roda (kN)': 'Maior_Impacto_kN'
        })
        .sort_values(by=['json_Identificação do veículo', 'Data'])
    )
    df_WCM_max['key'] = df_WCM_max['json_Identificação do veículo'].str.split().str[-1].astype(int)

    return df_WCM_max


# Rodar
wcm_trated = tratar_WCM(df_WCM)


wcm_trated

    json_Identificação do veículo        Data  Maior_Impacto_kN     key
0                      C30 076859  2025-10-03            151.10   76859
1                      C30 076859  2025-10-15            144.98   76859
2                      C30 076859  2025-10-31            142.23   76859
3                      C30 093090  2025-10-03            152.40   93090
4                      C30 093090  2025-10-15            150.25   93090
..                            ...         ...               ...     ...
400                    PCT 801691  2025-10-27             62.06  801691
401                    PCT 801704  2025-10-27             59.88  801704
402                    PCT 801780  2025-10-27             51.48  801780
403                    PCT 801836  2025-10-27             62.10  801836
404                    PCT 801852  2025-10-27             52.24  801852

[405 rows x 4 columns]

In [62]:
import pandas as pd


def concatenar_dados_new1_wcm_trated(df_new1, wcm_trated):
     

    wcm_trated_filtred = wcm_trated[wcm_trated["json_Identificação do veículo"].notna()]
    wcm_trated_filtred = wcm_trated_filtred[wcm_trated_filtred["Maior_Impacto_kN"].notna()]
    #wcm_trated_filtred['Data'] = pd.to_datetime(wcm_trated_filtred['Data'], format="%d/%m/%Y %H:%M:%S", errors='coerce')
    #wcm_trated_filtred['key'] = wcm_trated_filtred['key'].astype(int)

    df1 = df_new1
    df2 = wcm_trated_filtred

    # 1. Filtra apenas passagens com medição não nula
    df2_filtrado = df2[df2["Maior_Impacto_kN"].notnull()].copy()

    # 2. Ordena por equipamento e data (da mais recente para a mais antiga)
    df2_filtrado = df2_filtrado.sort_values(['key', 'Data'], ascending=[True, True])

    # ============================================================
    # A) PEGAR A ÚLTIMA MEDIÇÃO E A DATA DA ÚLTIMA MEDIÇÃO
    # ============================================================

    # Ordena por data DESC dentro da chave
    df2_desc = df2_filtrado.sort_values(['key', 'Data'], ascending=[True, False])

    # Pega a última linha por equipamento
    df_last = df2_desc.groupby('key').first().reset_index()

    df_last.rename(columns={
        'Maior_Impacto_kN': 'ultima_medicao',
        'Data': 'data_ultima_medicao'
    }, inplace=True)

    # ============================================================
    # B) PEGAR A MAIOR MEDIÇÃO ENTRE AS 3 ÚLTIMAS PASSAGENS
    # ============================================================

    # Pega rank das 3 últimas (já está ordenado ascendente)
    df2_filtrado['rank'] = df2_filtrado.groupby('key')['Data'].rank(method='first', ascending=False)

    df_top3 = df2_filtrado[df2_filtrado['rank'] <= 3]

    df_max = df_top3.groupby('key')['Maior_Impacto_kN'].max().reset_index()
    df_max.rename(columns={'Maior_Impacto_kN': 'max_medicao_ultimas_3'}, inplace=True)

    # ============================================================
    # C) MERGE FINAL
    # ============================================================

    df_final = df1.merge(df_max, on='key', how='left') \
                .merge(df_last[['key', 'ultima_medicao', 'data_ultima_medicao']], 
                        on='key', how='left')

    #df_final = df_final[["EQUNR","MODELO","STATUS","DATA_DE_FABRICACAO_trated","DATA_GARANTIA_trated","ULTIMA_RG","KM_RODADO_DESDE_ULTIMA_RG","max_medicao_ultimas_3","ultima_medicao","data_ultima_medicao","key"]]

    df_tratado = df_final.rename(columns={
        'max_medicao_ultimas_3' : 'WCM_max_medicao_ultimas_3',
        'ultima_medicao': 'WCM_ultima_medicao',
        'data_ultima_medicao': 'WCM_last_timestamp'
    })

    return df_tratado

df_new2 = concatenar_dados_new1_wcm_trated(df_new1, wcm_trated)
df_new2

,EQUNR,MODELO,STATUS,DATA_DE_FABRICACAO_trated,DATA_GARANTIA_trated,ULTIMA_RG,KM_RODADO_DESDE_ULTIMA_RG,TRKV_max_medicao_ultimas_3,TRKV_ultima_medicao,TRKV_last_timestamp,key,WCM_max_medicao_ultimas_3,WCM_ultima_medicao,WCM_last_timestamp
0,3502520PNQ,PLATAF. VP,1,2010-03-05,NaT,2010-04-21,78104.150,NaN,NaN,NaT,3502520,NaN,NaN,NaN
1,8418497HFT,GRANELEIROS,1,2006-10-06,2029-08-07,2024-08-08,155716.585,29.4386,29.4386,2025-11-19 02:45:37,8418497,NaN,NaN,NaN
2,8421200HFT,GRANELEIROS,1,2006-10-06,2030-05-13,2025-05-14,63865.552,26.5938,26.5938,2025-11-24 14:33:35,8421200,NaN,NaN,NaN
3,8423563HFT,GRANELEIROS,1,2006-10-06,2022-02-04,2003-04-19,724792.741,34.6456,34.6456,2025-10-13 19:15:35,8423563,NaN,NaN,NaN
4,6274358HNR,GÔNDOLAS VP,1,2010-03-09,NaT,2010-03-11,79492.020,NaN,NaN,NaT,6274358,117.67,113.91,2025-10-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14631,0554162HFT,GRANELEIROS,1,2011-01-25,2025-05-03,2006-01-26,412650.072,35.6108,33.2232,2025-11-08 16:35:24,554162,NaN,NaN,NaN
14632,0554103HFT,GRANELEIROS,1,2011-01-25,2022-11-14,2006-01-26,1466701.199,39.8780,39.8780,2025-11-06 09:44:16,554103,NaN,NaN,NaN
14633,0532363TCT,TANQUES,1,2008-03-14,2025-03-24,2003-03-16,321972.736,30.3784,29.4386,2025-11-22 08:13:19,532363,NaN,NaN,NaN
14634,0533459TCT,TANQUES,1,2008-05-09,2026-07-19,2010-04-11,199835.095,29.8958,29.8958,2025-11-18 10:20:14,533459,NaN,NaN,NaN
14635,0978779HFT,GRANELEIROS,1,2007-05-03,2024-10-05,2010-06-16,400183.867,60.2742,60.2742,2025-11-13 03:21:54,978779,NaN,NaN,NaN